spring:
  application:
    name: beverage
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vending_machine
    username: root
    password: 123456
